### ISSUE TITLE
File not found error (scrapy)

### ISSUE THREAD

**Issue by ajaybati** [huangmeng123/lit_char_data_wayback#2]
This is a great dataset by the way, and we wanted to use it for a group project we were doing. Unfortunately, we are running into some errors while following the steps. When I started the ./run.sh, the table was created, but something went wrong with scrapy. Here is the error output:

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/ajaybati/Downloads/lit_char_data_wayback/scraper/scraper/spiders/output/wayback_char_runtime.log'
`

`Traceback (most recent call last):
  File "main.py", line 138, in <module>
    main()
  File "main.py", line 76, in main
    dataset.filter_by_char_keys(char_keys)
  File "/Users/ajaybati/Downloads/lit_char_data_wayback/lib/book_char_dataset.py", line 34, in filter_by_char_keys
    self.book_lookup = {
  File "/Users/ajaybati/Downloads/lit_char_data_wayback/lib/book_char_dataset.py", line 35, in <dictcomp>
    book_key: self.book_lookup[book_key]
KeyError: ('Hatchet', 'sparknotes')`

For some reason, it is saying that there is some files missing in the github repo that we should have (i.e. output/ directory). Is this something we are doing wrong on our part? Any help would be appreciated!

**Comment by chtmp223** [comment]
I believe you have to create an `output` folder in this directory `'/Users/ajaybati/Downloads/lit_char_data_wayback/scraper/scraper/spiders/`. Hope this helps!
